---

- name: Make sure OpenSSL and python-pip is installed.
  become: true
  ansible.builtin.package:
    name: "{{ acme_server_packages }}"
    state: present
    update_cache: true
  run_once: true

- name: Make sure the needed pip module is installed.
  ansible.builtin.pip:
    name: "{{ acme_pip_packages }}"
    state: present
  run_once: true

- name: Make sure user exist.
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    state: present
  run_once: true

- name: Make sure the needed directory exists.
  become: true
  ansible.builtin.file:
    path: "{{ acme_files_dir }}/{{ item.domain }}"
    state: directory
    mode: "770"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user_group }}"
    recurse: true
  register: acme_files_dir_results
  run_once: true
  loop: "{{ acme_domains }}"
  loop_control:
    label: "{{ item.domain }}"

- name: Debug out the path.
  ansible.builtin.debug:
    msg:
      - "Directory {{ item.path }} is created/already exists."
  run_once: true
  loop: "{{ acme_files_dir_results.results }}"
  loop_control:
    label: "{{ item.item.domain }}"
  tags: [debug]
