---

- name: Generate an OpenSSL RSA 4096 private key for account for {{ acme_domain }}.
  community.crypto.openssl_privatekey:
    path: "{{ acme_private_account_key_dir }}"
    size: 4096
    type: RSA
  register: acme_account_private_key_results
  run_once: true

- name: Debug out the generated account key.
  ansible.builtin.debug:
    msg:
      - "The private key for Letsencrypt account is generated at {{ acme_account_private_key_results.filename }}."
  run_once: true
  tags: [debug]
