---

- name: Make sure files directory exists.
  ansible.builtin.file:
    path: "{{ cf_acme_tmp_dir }}"
    state: directory
    mode: "755"
  run_once: true

- name: Generate an OpenSSL RSA 4096 private key for accounts.
  community.crypto.openssl_privatekey:
    path: "{{ cf_acme_tmp_dir }}/{{ item.domain }}_account_private.key"
    size: 4096
    type: RSA
  loop: "{{ cf_acme_domains }}"
  loop_control:
    label: "{{ item.domain }}"
  register: acme_account_private_key_results
  run_once: true

- name: Debug out the generated account key.
  ansible.builtin.debug:
    msg: "The private key for Letsencrypt account is generated at {{ item.filename }}."
  loop: "{{ acme_account_private_key_results.results }}"
  loop_control:
    label: "{{ item.item.domain }}"
  run_once: true
  tags: [debug]
