---

- name: Generate an OpenSSL RSA 4096 private key for CSRs.
  community.crypto.openssl_privatekey:
    path: "files/{{ item.domain }}_cert_private.key"
    size: 4096
    type: RSA
  loop: "{{ acme_domains }}"
  loop_control:
    label: "{{ item.domain }}"
  register: acme_csr_private_key_results
  run_once: true

- name: Debug out the generated CSR private key.
  ansible.builtin.debug:
    msg:
      - "The private key for the CSR is generated at {{ item.filename }}."
  run_once: true
  loop: "{{ acme_csr_private_key_results.results }}"
  loop_control:
    label: "{{ item.item.domain }}"
  tags: [debug]

- name: Generate the CSRs.
  community.crypto.openssl_csr:
    path: "files/{{ item.domain }}.csr"
    privatekey_path: "files/{{ item.domain }}_cert_private.key"
    common_name: "*.{{ item.domain }}"
    email_address: "{{ acme_account_email }}"
    subject_alt_name: |
      {{
      [item.domain, '*.' + item.domain]
      | map('regex_replace', '^', 'DNS:')
      | list
      }}
  loop: "{{ acme_domains }}"
  loop_control:
    label: "{{ item.domain }}"
  run_once: true
  register: acme_csr_generate_result

- name: Debug out the generated CSR.
  ansible.builtin.debug:
    msg:
      - "The CSR is generated at {{ item.filename }}."
  run_once: true
  loop: "{{ acme_csr_generate_result.results }}"
  loop_control:
    label: "{{ item.item.domain }}"
  tags: [debug]
