---

- name: Create a challenge for the wildcard domain using account key file.
  community.crypto.acme_certificate:
    account_key_src: "{{ acme_cf_files_dir }}/{{ item.domain }}/{{ item.domain }}.account.private.key"
    account_email: "{{ acme_cf_account_email }}"
    src: "{{ acme_cf_files_dir }}/{{ item.domain }}/{{ item.domain }}.csr"
    cert: "{{ acme_cf_files_dir }}/{{ item.domain }}/{{ item.domain }}.crt"
    challenge: "dns-01"
    acme_directory: "{{ acme_cf_server_dir }}"
    remaining_days: "{{ acme_cf_remaining_days }}"
    acme_version: 2
    terms_agreed: true
  loop: "{{ acme_cf_domains }}"
  loop_control:
    label: "{{ item.domain }}"
  register: acme_cf_dns_challenge_results
  run_once: true

- name: Debug dns_challenge variable.
  ansible.builtin.debug:
    var: item
  run_once: true
  loop: "{{ acme_cf_dns_challenge_results.results }}"
  loop_control:
    label: "{{ item.item.domain }}"
  tags: [debug]

- name: Construct new lists for DNS-01 challenge.
  vars:
    _challenge_materials: []
  ansible.builtin.set_fact:
    _challenge_materials: |
      {{
        _challenge_materials + [
          {
            "challenge_data": item,
            "domain": item.item.domain,
            "domain_txt_value": item.challenge_data[item.item.domain]['dns-01'].resource_value | default(""),
            "domain_wildcard": "*." + item.item.domain,
            "domain_wildcard_txt_value": item.challenge_data["*." + item.item.domain]['dns-01'].resource_value | default (""),
            "alias_enabled": (acme_cf_domains | selectattr('domain', 'equalto', item.item.domain) | first).alias_enabled,
            "alias_zone": (acme_cf_domains | selectattr('domain', 'equalto',  item.item.domain) | first).alias_zone,
            "alias_record": (acme_cf_domains | selectattr('domain', 'equalto',  item.item.domain) | first).alias_record
          },
        ]
      }}
  run_once: true
  loop: "{{ acme_cf_dns_challenge_results.results }}"
  loop_control:
    label: "{{ item.item.domain }}"

- name: Debug out the constructed list.
  ansible.builtin.debug:
    var: _challenge_materials
  run_once: true
  tags: [debug]
