---

- name: Create TXT records for delegated domains.
  block:

    - name: Create TXT record using alias on Cloudflare (base).
      community.general.cloudflare_dns:
        zone: "{{ item.alias_zone }}"
        record: "{{ item.alias_record }}"
        type: TXT
        value: "{{ item.domain_txt_value }}"
        account_email: "{{ cf_acme_api_email }}"
        api_token: "{{ cf_acme_api_token }}"
        state: present
        solo: false
      when:
        - item.alias_enabled | default(false)
        - (item.domain_txt_value | length) > 0
      loop: "{{ _challenge_materials }}"
      loop_control:
        label: "{{ item.domain }}"
      run_once: true
      register: base_txt_generate_results

    - name: Create TXT record using alias on Cloudflare (wildcard).
      community.general.cloudflare_dns:
        zone: "{{ item.alias_zone }}"
        record: "{{ item.alias_record }}"
        type: TXT
        value: "{{ item.domain_wildcard_txt_value }}"
        account_email: "{{ cf_acme_api_email }}"
        api_token: "{{ cf_acme_api_token }}"
        state: present
        solo: false
      when:
        - item.alias_enabled | default(false)
        - (item.domain_wildcard_txt_value | length) > 0
      loop: "{{ _challenge_materials }}"
      loop_control:
        label: "{{ item.domain }}"
      run_once: true
      register: wildcard_txt_generate_results

- name: Create TXT records for non-delegated domains.
  block:

    - name: Create TXT record on Cloudflare (base).
      community.general.cloudflare_dns:
        zone: "{{ item.domain }}"
        record: "_acme-challenge"
        type: TXT
        value: "{{ item.domain_txt_value }}"
        account_email: "{{ cf_acme_api_email }}"
        api_token: "{{ cf_acme_api_token }}"
        state: present
        solo: false
      when:
        - not item.alias_enabled | default(false)
        - (item.domain_txt_value | length) > 0
      loop: "{{ _challenge_materials }}"
      loop_control:
        label: "{{ item.domain }}"
      run_once: true
      register: base_txt_generate_results

    - name: Create TXT record on Cloudflare (wildcard).
      community.general.cloudflare_dns:
        zone: "{{ item.domain }}"
        record: "_acme-challenge"
        type: TXT
        value: "{{ item.domain_wildcard_txt_value }}"
        account_email: "{{ cf_acme_api_email }}"
        api_token: "{{ cf_acme_api_token }}"
        state: present
        solo: false
      when:
        - not item.alias_enabled | default(false)
        - (item.domain_wildcard_txt_value | length) > 0
      loop: "{{ _challenge_materials }}"
      loop_control:
        label: "{{ item.domain }}"
      run_once: true
      register: wildcard_txt_generate_results
