---

- name: Setup var if using CNAME delegation.
  ansible.builtin.set_fact:
    _cf_zone: "{{ acme_cf_alias_zone }}"
    _cf_record: "{{ acme_cf_alias_record }}"
  when:
    - acme_cf_use_alias
    - acme_domain_txt_value is defined or acme_domain_wildcard_txt_value is defined

- name: Setup var.
  ansible.builtin.set_fact:
    _cf_zone: "{{ acme_domain }}"
    _cf_record: "_acme-challenge"
  when:
    - not acme_cf_use_alias
    - acme_domain_txt_value is defined or acme_domain_wildcard_txt_value is defined

- name: Create TXT record using alias on Cloudflare.
  community.general.cloudflare_dns:
    zone: "{{ _cf_zone }}"
    record: "{{ _cf_record }}"
    type: TXT
    value: "{{ item }}"
    account_email: "{{ acme_cf_api_email }}"
    api_token: "{{ acme_cf_api_token }}"
    state: present
    solo: false
  when: acme_domain_txt_value is defined or acme_domain_wildcard_txt_value is defined
  loop:
    - "{{ acme_domain_txt_value }}"
    - "{{ acme_domain_wildcard_txt_value }}"
  run_once: true
