---

- name: Wait for 30 seconds for domain propagation.
  ansible.builtin.pause:
    seconds: 30
  run_once: true
  when: |
    base_txt_generate_results is changed or
    base_txt_generate_results is changed

- name: Validate challenge and retrieve the cert and intermediate certificates.
  community.crypto.acme_certificate:
    account_key_src: "files/{{ item.domain }}_account_private.key"
    account_email: "{{ acme_account_email }}"
    src: "files/{{ item.domain }}.csr"
    cert: "files/{{ item.domain }}.crt"
    fullchain: "files/{{ item.domain }}_fullchain.crt"
    chain: "files/{{ item.domain }}_intermediate.crt"
    challenge: dns-01
    acme_directory: "{{ acme_server_dir }}"
    remaining_days: "{{ acme_remaining_days }}"
    acme_version: 2
    data: "{{ item.challenge_data }}"
  when: |
    (item.domain_txt_value | length) > 0 or
    (item.domain_wildcard_txt_value | length) > 0
  loop: "{{ _challenge_materials }}"
  loop_control:
    label: "{{ item.domain }}"
  register: validation_result
  retries: 5
  delay: 30
  until: validation_result is not failed
  run_once: true
