---

- name: Delete TXT records for delegated domains.
  block:

    - name: Delete TXT record using alias on Cloudflare (base).
      community.general.cloudflare_dns:
        zone: "{{ item.alias_zone }}"
        record: "{{ item.alias_record }}"
        type: TXT
        api_token: "{{ acme_cf_api_token }}"
        state: absent
      when:
        - item.alias_enabled | default(false)
        - (item.domain_txt_value | length) > 0
      loop: "{{ _challenge_materials }}"
      loop_control:
        label: "{{ item.domain }}"
      run_once: true

    - name: Delete TXT record using alias on Cloudflare (wildcard).
      community.general.cloudflare_dns:
        zone: "{{ item.alias_zone }}"
        record: "{{ item.alias_record }}"
        type: TXT
        api_token: "{{ acme_cf_api_token }}"
        state: absent
      when:
        - item.alias_enabled | default(false)
        - (item.domain_wildcard_txt_value | length) > 0
      loop: "{{ _challenge_materials }}"
      loop_control:
        label: "{{ item.domain }}"
      run_once: true

- name: Delete TXT records for non-delegated domains.
  block:
    - name: Delete TXT record on Cloudflare (base).
      community.general.cloudflare_dns:
        zone: "{{ item.domain }}"
        record: "_acme-challenge"
        type: TXT
        api_token: "{{ acme_cf_api_token }}"
        state: absent
      when:
        - not item.alias_enabled
        - (item.domain_txt_value | length) > 0
      loop: "{{ _challenge_materials }}"
      loop_control:
        label: "{{ item.domain }}"
      run_once: true

    - name: Delete TXT record on Cloudflare (wildcard).
      community.general.cloudflare_dns:
        zone: "{{ item.domain }}"
        record: "_acme-challenge"
        type: TXT
        api_token: "{{ acme_cf_api_token }}"
        state: absent
      when:
        - not item.alias_enabled | default(false)
        - (item.domain_wildcard_txt_value | length) > 0
      loop: "{{ _challenge_materials }}"
      loop_control:
        label: "{{ item.domain }}"
      run_once: true
