---

# details needed for ACME challenge.
cf_acme_domains: []

cf_acme_files_dir: "/tmp"
cf_acme_server_dir: "https://acme-staging-v02.api.letsencrypt.org/directory"
cf_acme_remaining_days: "30"
cf_acme_account_email: ""

# details needed for Cloudflare API authentication.
cf_acme_api_email: "{{ cf_acme_api_email | default(lookup('ansible.builtin.env', 'CF_API_EMAIL')) }}"
cf_acme_api_token: "{{ cf_acme_api_token | default(lookup('ansible.builtin.env', 'CF_API_TOKEN')) }}"

# details needed if you want to use an alias/CNAME delegation.
cf_acme_use_alias: false
cf_acme_alias_zone: "{{ cf_acme_alias_zone | default(omit) }}"
cf_acme_alias_record: "{{ cf_acme_alias_record | default(omit) }}"
