---

# details added to CSR, most of the time will not be used.
acme_cert_country_id: "{{ acme_cert_country_id | default(omit) }}"
acme_cert_org_name: "{{ acme_cert_org_name | default(omit) }}"

# details needed for ACME challenge.
acme_domain: "{{ acme_domain | undef(hint='You must specify the domain you want to generate the certificate for.') }}"
acme_files_dir: "{{ acme_files_dir | default('/tmp') }}"
acme_server_dir: "{{ acme_server_dir | default('https://acme-staging-v02.api.letsencrypt.org/directory') }}"
acme_remaining_days: "{{ acme_remaining_days | default('30') }}"
acme_account_email: "{{ acme_account_email | undef(hint='You must specify an email address for the ACME account.') }}"

# details needed for Cloudflare authentication, the default is using
# the environment variables CF_API_EMAIL and CF_API_TOKEN, but you
# can use anyway you want by overrriding the variables.
acme_cf_api_email: >
  {{ acme_cf_api_email
  | default(lookup('ansible.builtin.env', 'CF_API_EMAIL'))
  | undef(hint='You must specify an email address for the Cloudflare API.') }}
acme_cf_api_token: >
  {{ acme_cf_api_token
  | default(lookup('ansible.builtin.env', 'CF_API_TOKEN'))
  | undef(hint='You must specify an API token for the Cloudflare API.') }}

# details needed if you want to use an alias/CNAME delegation.
acme_cf_use_alias: "{{ acme_cf_use_alias | default(false) }}"
acme_cf_alias_zone: "{{ acme_cf_alias_zone | default(omit) }}"
acme_cf_alias_record: "{{ acme_cf_alias_record | default(omit) }}"
