---

name: Release to Ansible Galaxy.
on:
  push:
    tags:
      - 'v*'

jobs:
  release-to-galaxy:
    runs-on: ubuntu-latest
    steps:
      - name: Release to Ansible Galaxy.
        uses: ndkprd/actions/.github/workflows/ansible-release-to-galaxy.yaml@main
        with:
          release_tag: ${{ github.ref_name }}
          galaxy_api_key: ${{ secrets.GALAXY_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
