---

name: Release to Ansible Galaxy.
on:
  push:
    tags:
      - 'v*'

jobs:
  release-to-galaxy:
    uses: ndkprd/actions/ansible/ansible-release-to-galaxy.yaml@main
    secrets:
      galaxy_api_key: ${{ secrets.GALAXY_API_KEY }}
